CREATE TABLE papers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(512) NOT NULL COMMENT '论文标题',
    authors VARCHAR(512) NOT NULL COMMENT '作者列表',
    chapter VARCHAR(255) DEFAULT NULL COMMENT '所属章节或部分',
    url VARCHAR(1024) DEFAULT NULL COMMENT '论文链接'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='论文信息表';
